# Generated by Django 4.1.2 on 2022-10-24 16:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_CTA',
            field=models.CharField(help_text='Text to display on Call to Action', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_text',
            field=models.CharField(help_text='Write an introduction for the bakery', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_2',
            field=wagtail.fields.StreamField([('home_content_block', wagtail.blocks.StreamBlock([('heading_block', wagtail.blocks.StructBlock([('heading_text', wagtail.blocks.CharBlock(required=True)), ('size', wagtail.blocks.ChoiceBlock(choices=[('DEFAULT', 'Select a header size'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4')], required=False))], icon='title')), ('paragraph_block', wagtail.blocks.RichTextBlock(icon='')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False))], icon='image')), ('block_quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(required=True)), ('author', wagtail.blocks.CharBlock(label='e.g. Mary Berry', required=False))], icon='')), ('embed_block', wagtail.embeds.blocks.EmbedBlock(help_text='Insert an embed URL e.g. https://www.youtube.com/watch?v=SGJFWirQ3ks', icon=''))], icon='arrow-down-big'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='section_3',
            field=wagtail.fields.StreamField([('section_3', wagtail.blocks.StructBlock([('featured_section_1_title', wagtail.blocks.CharBlock(help_text='Title to display above the promo copy', icon='', required=False)), ('featured_section_1', wagtail.blocks.PageChooserBlock(help_text='First featured section for the homepage. Will display up to three child items.', required=False)), ('featured_section_2_title', wagtail.blocks.CharBlock(help_text='Title to display above the promo copy', icon='', required=False)), ('featured_section_2', wagtail.blocks.PageChooserBlock(help_text='Second featured section for the homepage. Will display up to three child items.', required=False)), ('featured_section_3_title', wagtail.blocks.CharBlock(help_text='Title to display above the promo copy', icon='', required=False)), ('featured_section_3', wagtail.blocks.PageChooserBlock(help_text='Third featured section for the homepage. Will display up to six child items.', required=False))], icon='arrow-down-big'))], blank=True, use_json_field=True),
        ),
    ]
