# Generated by Django 4.1.2 on 2022-10-24 18:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0003_projectpage_remove_fktpage_name_remove_fktpage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='gender',
            field=models.CharField(choices=[('DEFAULT', 'Select a gender'), ('MALE', 'male'), ('FEMALE', 'female')], default='DEFAULT', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXXXXXXXXXXX'.", regex='^\\+?1?\\d{12,12}$')]),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='requested_role',
            field=models.CharField(choices=[('visitor', 'VISITOR'), ('moderator', 'MODERATOR'), ('admin', 'ADMIN')], default='VISITOR', max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='university',
            field=models.CharField(default='Belarusian State University of Informatics and Radioelectronics', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='username',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
