# Generated by Django 4.1.2 on 2022-10-24 18:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0004_projectpage_email_projectpage_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder', models.CharField(max_length=64, null=True)),
                ('foundation_date', models.DateField(null=True)),
                ('acronym', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXX-XX-XXX-XX-XX'. e.g. +375291234567", regex='^\\+?1?\\d{12,12}$')]),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fktprojects.university'),
        ),
    ]
