# Generated by Django 4.1.2 on 2022-10-24 18:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0005_university_alter_projectpage_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='phone_number',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+XXX-XX-XXX-XX-XX', e.g. +375291234567.", regex='^\\+?1?\\d{12,12}$')]),
        ),
    ]
