# Generated by Django 4.1.2 on 2022-10-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0006_alter_projectpage_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='university',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='acronym',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='foundation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='founder',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
