# Generated by Django 4.1.2 on 2022-10-24 19:30

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0007_remove_projectpage_university_projectpage_acronym_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='user <django.db.models.fields.CharField> created at 24/10/2022 19:30:48', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='marker',
            field=colorfield.fields.ColorField(blank=True, choices=[('#FF0000', 'red'), ('#0000FF', 'blue'), ('#00FF00', 'green'), ('#000000', 'black'), ('#808080', 'grey')], default='#FF0000', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Select status'), ('PLANNING', 'planning'), ('PROCESSING', 'processing'), ('FINISHED', 'finished')], default='DEFAULT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='gender',
            field=models.CharField(choices=[('DEFAULT', 'Choose a gender'), ('MALE', 'male'), ('FEMALE', 'female')], default='DEFAULT', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='requested_role',
            field=models.CharField(choices=[('DEFAULT', 'Select role'), ('VISITOR', 'visitor'), ('MODERATOR', 'moderator'), ('ADMIN', 'admin')], default='DEFAULT', max_length=9, null=True),
        ),
    ]
