# Generated by Django 4.1.2 on 2022-10-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0008_projectpage_info_projectpage_marker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='user <django.db.models.fields.CharField> created at 24/10/2022 19:32:29', max_length=50, null=True),
        ),
    ]
