# Generated by Django 4.1.2 on 2022-10-24 19:46

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0009_alter_projectpage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='user user created at 24/10/2022 19:46:44', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='marker',
            field=wagtail_color_panel.fields.ColorField(choices=[('#FF0000', 'red'), ('#0000FF', 'blue'), ('#00FF00', 'green'), ('#000000', 'black'), ('#808080', 'grey')], default='#FF0000', max_length=7, null=True),
        ),
    ]
