# Generated by Django 4.1.2 on 2022-10-24 19:52

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0010_alter_projectpage_info_alter_projectpage_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='user user created at 24/10/2022 19:52:58', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='marker',
            field=wagtail_color_panel.fields.ColorField(choices=[('RED', '#FF0000'), ('BLUE', '#0000FF'), ('GREEN', '#00FF00'), ('BLACK', '#000000'), ('GREY', '#808080')], default='RED', max_length=7, null=True),
        ),
    ]
