# Generated by Django 4.1.2 on 2022-10-24 20:04

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fktprojects', '0011_alter_projectpage_info_alter_projectpage_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='info',
            field=models.CharField(default='user user created at 24/10/2022 20:04:15', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='marker',
            field=wagtail_color_panel.fields.ColorField(default='#FF0000', max_length=7, null=True),
        ),
    ]
